package org.tax.model;

public class TaxFavouriteAnswer extends TaxFavouriteAnswerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_favourite_answer.question_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_favourite_answer.answer_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    private Integer answerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_favourite_answer.user_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_favourite_answer.question_id
     *
     * @return the value of tax_favourite_answer.question_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_favourite_answer.question_id
     *
     * @param questionId the value for tax_favourite_answer.question_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_favourite_answer.answer_id
     *
     * @return the value of tax_favourite_answer.answer_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    public Integer getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_favourite_answer.answer_id
     *
     * @param answerId the value for tax_favourite_answer.answer_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    public void setAnswerId(Integer answerId) {
        this.answerId = answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_favourite_answer.user_id
     *
     * @return the value of tax_favourite_answer.user_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_favourite_answer.user_id
     *
     * @param userId the value for tax_favourite_answer.user_id
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}