package org.tax.model;

public class TaxMessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_message.id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_message.id
     *
     * @return the value of tax_message.id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_message.id
     *
     * @param id the value for tax_message.id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}