package org.tax.model;

import lombok.Data;

@Data
public class TaxMessage extends TaxMessageKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_message.sender_id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    private String senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_message.receiver_id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    private String receiverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_message.content
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_message.status
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    private Byte status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_message.sender_id
     *
     * @return the value of tax_message.sender_id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public String getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_message.sender_id
     *
     * @param senderId the value for tax_message.sender_id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public void setSenderId(String senderId) {
        this.senderId = senderId == null ? null : senderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_message.receiver_id
     *
     * @return the value of tax_message.receiver_id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_message.receiver_id
     *
     * @param receiverId the value for tax_message.receiver_id
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_message.content
     *
     * @return the value of tax_message.content
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_message.content
     *
     * @param content the value for tax_message.content
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_message.status
     *
     * @return the value of tax_message.status
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_message.status
     *
     * @param status the value for tax_message.status
     *
     * @mbg.generated Sat Jul 07 16:10:55 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}