package org.tax.model;

import java.util.Date;

public class TaxMessageReply extends TaxMessageReplyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_message_reply.message_id
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    private Integer messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_message_reply.content
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_message_reply.publish_date
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    private Date publishDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_message_reply.message_id
     *
     * @return the value of tax_message_reply.message_id
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_message_reply.message_id
     *
     * @param messageId the value for tax_message_reply.message_id
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_message_reply.content
     *
     * @return the value of tax_message_reply.content
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_message_reply.content
     *
     * @param content the value for tax_message_reply.content
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_message_reply.publish_date
     *
     * @return the value of tax_message_reply.publish_date
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_message_reply.publish_date
     *
     * @param publishDate the value for tax_message_reply.publish_date
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }
}