package org.tax.model;

public class TaxQuestionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_question.id
     *
     * @mbg.generated Tue Jul 10 18:08:12 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_question.id
     *
     * @return the value of tax_question.id
     *
     * @mbg.generated Tue Jul 10 18:08:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_question.id
     *
     * @param id the value for tax_question.id
     *
     * @mbg.generated Tue Jul 10 18:08:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}