package org.tax.model;

public class TaxQuestionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_question.id
     *
     * @mbg.generated Sat Jul 07 16:08:58 CST 2018
     */
    private String id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_question.id
     *
     * @return the value of tax_question.id
     *
     * @mbg.generated Sat Jul 07 16:08:58 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_question.id
     *
     * @param id the value for tax_question.id
     *
     * @mbg.generated Sat Jul 07 16:08:58 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }
}