package org.tax.model;

public class TaxQuestionPro extends TaxQuestionProKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_question_pro.question_id
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_question_pro.pro_id
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    private Integer proId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_question_pro.question_id
     *
     * @return the value of tax_question_pro.question_id
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_question_pro.question_id
     *
     * @param questionId the value for tax_question_pro.question_id
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_question_pro.pro_id
     *
     * @return the value of tax_question_pro.pro_id
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_question_pro.pro_id
     *
     * @param proId the value for tax_question_pro.pro_id
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }
}