package org.tax.model;

public class TaxUserPro extends TaxUserProKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_user_pro.pro_id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    private Integer proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_user_pro.user_id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_user_pro.pro_id
     *
     * @return the value of tax_user_pro.pro_id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_user_pro.pro_id
     *
     * @param proId the value for tax_user_pro.pro_id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_user_pro.user_id
     *
     * @return the value of tax_user_pro.user_id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_user_pro.user_id
     *
     * @param userId the value for tax_user_pro.user_id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}