package org.tax.model;

public class TaxUserProKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_user_pro.id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_user_pro.id
     *
     * @return the value of tax_user_pro.id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_user_pro.id
     *
     * @param id the value for tax_user_pro.id
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }
}