package org.tax.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.tax.model.TaxFavouriteAnswer;
import org.tax.model.TaxFavouriteAnswerExample;
import org.tax.model.TaxFavouriteAnswerKey;

public interface TaxFavouriteAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    long countByExample(TaxFavouriteAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    int deleteByExample(TaxFavouriteAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    @Delete({
        "delete from tax_favourite_answer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TaxFavouriteAnswerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    @Insert({
        "insert into tax_favourite_answer (id, question_id, ",
        "answer_id, user_id)",
        "values (#{id,jdbcType=INTEGER}, #{questionId,jdbcType=INTEGER}, ",
        "#{answerId,jdbcType=INTEGER}, #{userId,jdbcType=VARCHAR})"
    })
    int insert(TaxFavouriteAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    int insertSelective(TaxFavouriteAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    List<TaxFavouriteAnswer> selectByExample(TaxFavouriteAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    @Select({
        "select",
        "id, question_id, answer_id, user_id",
        "from tax_favourite_answer",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("org.tax.dao.TaxFavouriteAnswerMapper.BaseResultMap")
    TaxFavouriteAnswer selectByPrimaryKey(TaxFavouriteAnswerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaxFavouriteAnswer record, @Param("example") TaxFavouriteAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    int updateByExample(@Param("record") TaxFavouriteAnswer record, @Param("example") TaxFavouriteAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    int updateByPrimaryKeySelective(TaxFavouriteAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite_answer
     *
     * @mbg.generated Wed Jul 18 17:02:39 CST 2018
     */
    @Update({
        "update tax_favourite_answer",
        "set question_id = #{questionId,jdbcType=INTEGER},",
          "answer_id = #{answerId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaxFavouriteAnswer record);
}