package org.tax.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.tax.model.TaxFavourite;
import org.tax.model.TaxFavouriteExample;
import org.tax.model.TaxFavouriteKey;

public interface TaxFavouriteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    long countByExample(TaxFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    int deleteByExample(TaxFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    @Delete({
        "delete from tax_favourite",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TaxFavouriteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    @Insert({
        "insert into tax_favourite (id, question_id, ",
        "user_id)",
        "values (#{id,jdbcType=INTEGER}, #{questionId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=VARCHAR})"
    })
    int insert(TaxFavourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    int insertSelective(TaxFavourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    List<TaxFavourite> selectByExample(TaxFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    @Select({
        "select",
        "id, question_id, user_id",
        "from tax_favourite",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("org.tax.dao.TaxFavouriteMapper.BaseResultMap")
    TaxFavourite selectByPrimaryKey(TaxFavouriteKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaxFavourite record, @Param("example") TaxFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    int updateByExample(@Param("record") TaxFavourite record, @Param("example") TaxFavouriteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    int updateByPrimaryKeySelective(TaxFavourite record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_favourite
     *
     * @mbg.generated Sat Jul 07 16:10:40 CST 2018
     */
    @Update({
        "update tax_favourite",
        "set question_id = #{questionId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaxFavourite record);
}