package org.tax.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.tax.model.TaxInvitation;
import org.tax.model.TaxInvitationExample;
import org.tax.model.TaxInvitationKey;

public interface TaxInvitationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    long countByExample(TaxInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    int deleteByExample(TaxInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    @Delete({
        "delete from tax_invitation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TaxInvitationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    @Insert({
        "insert into tax_invitation (id, question_id, ",
        "user_id)",
        "values (#{id,jdbcType=INTEGER}, #{questionId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=VARCHAR})"
    })
    int insert(TaxInvitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    int insertSelective(TaxInvitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    List<TaxInvitation> selectByExample(TaxInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    @Select({
        "select",
        "id, question_id, user_id",
        "from tax_invitation",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("org.tax.dao.TaxInvitationMapper.BaseResultMap")
    TaxInvitation selectByPrimaryKey(TaxInvitationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaxInvitation record, @Param("example") TaxInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    int updateByExample(@Param("record") TaxInvitation record, @Param("example") TaxInvitationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    int updateByPrimaryKeySelective(TaxInvitation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_invitation
     *
     * @mbg.generated Sat Jul 07 16:09:44 CST 2018
     */
    @Update({
        "update tax_invitation",
        "set question_id = #{questionId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaxInvitation record);
}