package org.tax.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.tax.VO.MessageReplyVO;
import org.tax.model.TaxMessageReply;
import org.tax.model.TaxMessageReplyExample;
import org.tax.model.TaxMessageReplyKey;

public interface TaxMessageReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    long countByExample(TaxMessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    int deleteByExample(TaxMessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    @Delete({
        "delete from tax_message_reply",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TaxMessageReplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    @Insert({
        "insert into tax_message_reply (id, message_id, ",
        "content, publish_date)",
        "values (#{id,jdbcType=INTEGER}, #{messageId,jdbcType=INTEGER}, ",
        "#{content,jdbcType=VARCHAR}, #{publishDate,jdbcType=DATE})"
    })
    int insert(TaxMessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    int insertSelective(TaxMessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    List<TaxMessageReply> selectByExample(TaxMessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    @Select({
        "select",
        "id, message_id, content, publish_date",
        "from tax_message_reply",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("org.tax.dao.TaxMessageReplyMapper.BaseResultMap")
    TaxMessageReply selectByPrimaryKey(TaxMessageReplyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaxMessageReply record, @Param("example") TaxMessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    int updateByExample(@Param("record") TaxMessageReply record, @Param("example") TaxMessageReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    int updateByPrimaryKeySelective(TaxMessageReply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_message_reply
     *
     * @mbg.generated Fri Jul 20 10:36:17 CST 2018
     */
    @Update({
        "update tax_message_reply",
        "set message_id = #{messageId,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "publish_date = #{publishDate,jdbcType=DATE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaxMessageReply record);

	List<MessageReplyVO> selectByMessage(int messageId);
}