package org.tax.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.tax.model.TaxPro;
import org.tax.model.TaxProExample;
import org.tax.model.TaxProKey;

public interface TaxProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    long countByExample(TaxProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    int deleteByExample(TaxProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    @Delete({
        "delete from tax_pro",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TaxProKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    @Insert({
        "insert into tax_pro (id, name)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR})"
    })
    int insert(TaxPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    int insertSelective(TaxPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    List<TaxPro> selectByExample(TaxProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    @Select({
        "select",
        "id, name",
        "from tax_pro",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("org.tax.dao.TaxProMapper.BaseResultMap")
    TaxPro selectByPrimaryKey(TaxProKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaxPro record, @Param("example") TaxProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    int updateByExample(@Param("record") TaxPro record, @Param("example") TaxProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    int updateByPrimaryKeySelective(TaxPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_pro
     *
     * @mbg.generated Sat Jul 07 16:09:30 CST 2018
     */
    @Update({
        "update tax_pro",
        "set name = #{name,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaxPro record);
}