package org.tax.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.tax.model.TaxQuestion;
import org.tax.model.TaxQuestionPro;
import org.tax.model.TaxQuestionProExample;
import org.tax.model.TaxQuestionProKey;

public interface TaxQuestionProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    long countByExample(TaxQuestionProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    int deleteByExample(TaxQuestionProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    @Delete({
        "delete from tax_question_pro",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TaxQuestionProKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    @Insert({
        "insert into tax_question_pro (id, question_id, ",
        "pro_id)",
        "values (#{id,jdbcType=INTEGER}, #{questionId,jdbcType=INTEGER}, ",
        "#{proId,jdbcType=INTEGER})"
    })
    int insert(TaxQuestionPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    int insertSelective(TaxQuestionPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    List<TaxQuestion> selectByExample(TaxQuestionProExample example);
    
    List<TaxQuestion> ultimateSelect(TaxQuestionProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    @Select({
        "select",
        "id, question_id, pro_id",
        "from tax_question_pro",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("org.tax.dao.TaxQuestionProMapper.BaseResultMap")
    TaxQuestionPro selectByPrimaryKey(TaxQuestionProKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaxQuestionPro record, @Param("example") TaxQuestionProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    int updateByExample(@Param("record") TaxQuestionPro record, @Param("example") TaxQuestionProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    int updateByPrimaryKeySelective(TaxQuestionPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_question_pro
     *
     * @mbg.generated Sat Jul 21 13:46:30 CST 2018
     */
    @Update({
        "update tax_question_pro",
        "set question_id = #{questionId,jdbcType=INTEGER},",
          "pro_id = #{proId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaxQuestionPro record);
    
    long countByCustomedCondition(TaxQuestionProExample example);

	long ultimateCount(TaxQuestionProExample example);
}