package org.tax.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.tax.model.TaxShare;
import org.tax.model.TaxShareExample;
import org.tax.model.TaxShareKey;

public interface TaxShareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    long countByExample(TaxShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    int deleteByExample(TaxShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    @Delete({
        "delete from tax_share",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TaxShareKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    @Insert({
        "insert into tax_share (id, author_id, ",
        "title, content, ",
        "publish_date, click, ",
        "likes, favourite)",
        "values (#{id,jdbcType=INTEGER}, #{authorId,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{publishDate,jdbcType=DATE}, #{click,jdbcType=INTEGER}, ",
        "#{likes,jdbcType=INTEGER}, #{favourite,jdbcType=INTEGER})"
    })
    int insert(TaxShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    int insertSelective(TaxShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    List<TaxShare> selectByExample(TaxShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    @Select({
        "select",
        "id, author_id, title, content, publish_date, click, likes, favourite",
        "from tax_share",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("org.tax.dao.TaxShareMapper.BaseResultMap")
    TaxShare selectByPrimaryKey(TaxShareKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaxShare record, @Param("example") TaxShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    int updateByExample(@Param("record") TaxShare record, @Param("example") TaxShareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    int updateByPrimaryKeySelective(TaxShare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_share
     *
     * @mbg.generated Sat Jul 07 16:10:16 CST 2018
     */
    @Update({
        "update tax_share",
        "set author_id = #{authorId,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "publish_date = #{publishDate,jdbcType=DATE},",
          "click = #{click,jdbcType=INTEGER},",
          "likes = #{likes,jdbcType=INTEGER},",
          "favourite = #{favourite,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaxShare record);
}