package org.tax.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.tax.model.TaxUserPro;
import org.tax.model.TaxUserProExample;
import org.tax.model.TaxUserProKey;

public interface TaxUserProMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    long countByExample(TaxUserProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    int deleteByExample(TaxUserProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    @Delete({
        "delete from tax_user_pro",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(TaxUserProKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    @Insert({
        "insert into tax_user_pro (id, pro_id, ",
        "user_id)",
        "values (#{id,jdbcType=INTEGER}, #{proId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=VARCHAR})"
    })
    int insert(TaxUserPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    int insertSelective(TaxUserPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    List<TaxUserPro> selectByExample(TaxUserProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    @Select({
        "select",
        "id, pro_id, user_id",
        "from tax_user_pro",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("org.tax.dao.TaxUserProMapper.BaseResultMap")
    TaxUserPro selectByPrimaryKey(TaxUserProKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") TaxUserPro record, @Param("example") TaxUserProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    int updateByExample(@Param("record") TaxUserPro record, @Param("example") TaxUserProExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    int updateByPrimaryKeySelective(TaxUserPro record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tax_user_pro
     *
     * @mbg.generated Mon Jul 16 12:03:41 CST 2018
     */
    @Update({
        "update tax_user_pro",
        "set pro_id = #{proId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TaxUserPro record);
}